# action.yml
name: 'prgTW-rector'
branding:
    icon: check
    color: green
description: 'Process files using Rector'
inputs:
    args:
        description: 'Arguments passed to rector binary'
        required: true
        default: 'process --dry-run --ansi'
outputs:
    exit_code:
        description: Exit code from rector
runs:
    using: 'docker'
    image: 'Dockerfile'
    args:
        - ${{ inputs.args }}
